###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = pkill rofi || bash ~/.config/rofi/scripts/launcher.sh
$browser = brave --disable-features=UseOzonePlatform --ozone-platform=wayland
$swaync = swaync-client -t
